uploads = []
outputs = []

[[generated]]
id = "QO97fvnk8VmGDBD8JQFjd"
uri = "file://artifacts/questly/public/feature-quiz.png"
type = "image"
title = "quiz feature illustration"

[[generated]]
id = "fhgnrQ3nESo_n_qDdNs9f"
uri = "file://artifacts/questly/public/feature-summary.png"
type = "image"
title = "summary feature illustration"

[[generated]]
id = "uaL0K74fIwt-_A91pncrJ"
uri = "file://artifacts/questly/public/feature-flashcards.png"
type = "image"
title = "flashcards feature illustration"

[[generated]]
id = "a7MhEbrjyz0QqGsneaHoc"
uri = "file://artifacts/questly/public/feature-progress.png"
type = "image"
title = "progress tracking illustration"

[[generated]]
id = "K9olWUbpztSwbIbB-RMpf"
uri = "file://artifacts/questly/public/logo.png"
type = "image"
title = "quizmi logo icon"

[[generated]]
id = "gspgvkcqZhUWJCs30iVE-"
uri = "file://artifacts/questly/public/study-1.png"
type = "image"
title = "student studying cafe"

[[generated]]
id = "UGKRzZsn3vE6hTIbyKFM5"
uri = "file://artifacts/questly/public/study-2.png"
type = "image"
title = "student library studying"

[[generated]]
id = "ZgQ6Cg7yVe1T03TbFhz4L"
uri = "file://artifacts/questly/public/study-3.png"
type = "image"
title = "group study session"
